-- Autocmds are automatically loaded on the VeryLazy event
-- Default autocmds that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/autocmds.lua
-- Add any additional autocmds here
-- local time = os.date("*t")
-- if time.hour >= 8 and time.hour < 20 then
--   vim.opt.background = "light"
-- else
--   vim.opt.background = "dark"
-- end
-- vim.opt.background = "dark"
